# Generated by Django 5.2.5 on 2025-09-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "preview",
                    models.ImageField(blank=True, null=True, upload_to="blog_previews/", verbose_name="Preview"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creation date")),
                ("is_published", models.BooleanField(default=False, verbose_name="Published")),
                ("views_count", models.PositiveIntegerField(default=0, verbose_name="Views")),
            ],
        ),
    ]
