# Generated by Django 5.2.5 on 2025-09-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["title"], "verbose_name": "пост", "verbose_name_plural": "посты"},
        ),
        migrations.AlterField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Published"),
        ),
    ]
