# Определяем события
events {
    # Устанавливаем максимальное количество соединений
    worker_connections 1024;
}

# Определяем основной http-блок
http {
    # Помогаем браузеру правильно определить и обрабатывать разные типы файлов
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    # Определяем сервер для django-приложения
    upstream django {
        # Указываем сервис web и порт 8000
        server web:8000;
    }
    # Настраиваем сервер
    server {
        # Слушаем на порту 80
        listen 80;
        # Имя сервера оставляем по-умолчанию
        server_name _;
        # Определяем обработку запросов к статическим файлам
        location /static/ {
            # Указываем путь к статическим файлам в контейнере
            alias /app/staticfiles/;
        }
        # Определяем обработку запросов к медиа файлам
        location /media/ {
            # Указываем путь к медиа файлам в контейнере
            alias /app/media/;
        }
        # Проксируем остальные зпросы к django-приложению
        location / {
            proxy_pass http://django/;
        }
    }
}
